### ISSUE TITLE
Questionaire Responses

### ISSUE THREAD

**Issue by Itskiprotich** [google/android-fhir#1032] opened 2022-01-13 05:40 UTC
**Describe the bug**
Updated both the Fhir Engine and the Datacapture libraries to the latest versions. Upon submiting a questionaire, the app crashes with the error as shown below

**Component**
SDC library

**To Reproduce**
1. Have the latest updates on libraries. Go to patient's details, complete a survey
2. Click on the submit button
3. Scroll down to logs and see the line creating the error

**Expected behavior**
Upon submitting the data, it was my expected to get the data saved and like the previous versions

**Screenshots**
![image](https://user-images.githubusercontent.com/26279422/149271943-1e983914-5839-4d87-97d1-12a814ef9b00.png)

**Smartphone (please complete the following information):**
 - Device: Techno LC6a
 - Android version: 9
 - Build number: LC6a
 - Version 28

**Additional context**
N/A

**Would you like to work on the issue?**
I am still learning the FHIR Engine and the associated libraries

**Comment by Tarun-Bhardwaj** [comment] 2022-01-17 14:20
Closing this issue as it's a duplicate of #1029

**Closed by Tarun-Bhardwaj** 2022-01-17 14:20 UTC
Labels: Bug
