### ISSUE TITLE
Not able to build android-FHIR engine project

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#950] opened 2021-11-30 05:50 UTC
Getting below error
<img width="1424" alt="143430168-5961b0f2-3dfc-4730-9214-1314c2b01559" src="https://user-images.githubusercontent.com/64417713/143992831-52ba7911-d047-4640-8f74-e6068555f88f.png">
:

**Comment by jingtang10** [comment] 2021-12-01 09:10
thanks for creating this. can you add who reported this issue and more details on their setup?

**Comment by anita-vadverao** [comment] 2021-12-01 10:20
@MUzairS15 Can you please provide more details about setup and failure?

**Comment by MUzairS15** [comment] 2021-12-02 04:46
Android Studio: 2020.3.1
Gradle Version: 7.2
JDK: 16.0.1
OS: MacOS BigSur, 
Machine: ARM based
java.lang.IllegalAccessError: class org.jetbrains.kotlin.kapt3.base.KaptContext (in unnamed module @0x434946a1) cannot access class com.sun.tools.javac.util.Context (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.util to unnamed module @0x434946a1
<img width="1280" alt="Screenshot 2021-12-02 at 10 11 30 AM" src="https://user-images.githubusercontent.com/79860504/144359385-1d53e56e-5421-4def-9aed-481e767d59d6.png">

**Comment by MUzairS15** [comment] 2021-12-02 04:46
Pls, let me know if anything else is required.

**Comment by Tarun-Bhardwaj** [comment] 2021-12-15 09:25
@anita-vadverao , @aditya-07 is there any update/next step identified for this issue?

**Comment by jingtang10** [comment] 2022-01-05 09:32
@MUzairS15 have you been able to solve the issue? sorry for the delay

**Comment by Tarun-Bhardwaj** [comment] 2022-04-20 07:37
@MUzairS15 , are you still facing this issue?

**Comment by Tarun-Bhardwaj** [comment] 2022-05-06 11:30
Closing this issue as it is not reproducible.

**Closed by Tarun-Bhardwaj** 2022-05-06 11:30 UTC
Labels: FHIR engine, Triage
