### ISSUE TITLE
Validation : Initially modal and open choice view shows error message if answer is empty.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1514] opened 2022-07-28 12:41 UTC
**Describe the bug**
Modal and open choice view shows error message initially if answer is empty

**Component**
SDC library.

**To Reproduce**

1. Open catalog app.
2. Click on the Modal view.
3. Click on the gear icon, it opens the bottom sheet.
4. Click on the “Show error state”

**Expected behavior**
Initially, it does not show validation error message.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment] 2022-07-29 12:07
this should be fixed by #1468 ?

**Comment by jingtang10** [comment] 2022-08-24 04:22
i think this should be fixed by #1468 . please verify @santosh-pingle

**Comment by fredhersch** [comment] 2022-08-30 07:15
@santosh-pingle can you confirm if this is fixed?

**Comment by santosh-pingle** [comment] 2022-09-02 06:27
It's reproducible.

**Comment by aurangzaibumer** [comment] 2022-09-02 10:07
https://user-images.githubusercontent.com/35099184/188116008-b3d5212a-eb12-43a6-ab66-4546cc62e126.mp4

Tried this, it is working fine for me _(Not showing validation error on start)_

Emulator details
Pixel 4A
Android version 12 
sdk_gphone64_x86_64-userdebug 12 SE1A.220203.002.A1 8151367 dev-keys

cc @f-odhiambo

**Comment by Tarun-Bhardwaj** [comment] 2022-09-14 07:49
@santosh-pingle , could you please confirm if this is still reproducible?

**Comment by santosh-pingle** [comment] 2022-09-19 06:20
Issue is reproducible.
Me and @aurangzaibumer  already had discussion on it.
He already proposed draft, which he supposed to share with @f-odhiambo as per offline discussion with Umer.

**Comment by jingtang10** [comment] 2022-09-28 16:17
@aurangzaibumer do you have any update/ETA for this? thanks

**Comment by aurangzaibumer** [comment] 2022-10-04 07:19
> @aurangzaibumer do you have any update/ETA for this? thanks

Have investigated the issue and there are two possibilities to solve this problem
1. to introduce/add a new field on questionnaireItemViewItem that checks if answers is either being modified/add/deleted by the caller. In that way we will able to apply check before calling clearAnswer method. If User has not updated/added/answer in that case we wouldn't call clearAnswer.

2. to make answers variable in questionnaireitemviewitem nullable and initialize it when answer is either being added/modified/deleted but haven't tried this out because it has a very huge impact on all view factories and its usage is almost on all view factories.

@jingtang10 Please review and suggest which one you think is more suitable. 

cc @f-odhiambo

**Comment by jingtang10** [comment] 2022-11-03 11:42
similar to https://github.com/google/android-fhir/blob/4e88f68e1d586d9ad423951cc86d3957fb891c2b/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt#L108

i think what you need to do is to make sure if the answer is not validated you don't show any error.

**Comment by santosh-pingle** [comment] 2023-03-09 09:44
Looking into it, thanks!

**Closed** 2023-04-25 17:12 UTC
Labels: type:bug, P2, effort:xsmall, ux
