### ISSUE TITLE
[R&D] Ability to update APK and or FHIR resources without internet

### ISSUE THREAD

**Issue by mberg** [google/android-fhir#275] opened 2021-02-23 20:58 UTC
In the context of CHW program in Liberia, we may have users who work offline for months at a time.  In this context, the way they sync data is via P2P with a visiting supervisor who downloads new activity from their device which is then submitted to the server when the supervisor gains access to the Internet.

In this example, it would be ideal if we can do support 2 things.

1 - We would want to update the content of the app. Eg. Questionnaire changes.  We assume this can be just part of the modified resources that would be part of the P2P sync.

2 - Ability to upgrade the APK itself.  Hopefully, with the ability to modify content via FHIR this is not needed as often.  Since the SDK/APK will be rapidly evolving having the ability to do this though would be great.

**Comment by jingtang10** [comment] 2021-03-05 01:08
thanks matt!

1. can you share the p2p library you'll be using?
2. i don't think we ever want to update the sdk without updating the apk. so this really is a question of how to update apps. play store does some clever stuff but i don't know they are applicable in the offline setting where you probably just want to adb install. i think this item is out-of-scope for this codebase.

**Comment by pld** [comment] 2021-03-05 01:32
This is the p2p library OpenSRP currently uses, https://github.com/OpenSRP/android-p2p-sync

On (2) agree, oos

**Comment by jingtang10** [comment] 2021-03-24 16:53
I'll close this and mark as duplicate of https://github.com/google/android-fhir/issues/258 where we should continue the discussion.

**Closed** 2021-03-25 10:07 UTC
Labels: duplicate, exploring
