### ISSUE TITLE
Support readonly element in questionnaire. 

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#817] opened 2021-10-07 08:53 UTC
**Describe the bug**

Read only element should not be edited.
http://build.fhir.org/ig/HL7/sdc/rendering.html#other

**This issue is a duplicate of https://github.com/google/android-fhir/issues/763**

**Component**
SDC library

**To Reproduce**

**Expected behavior**
Read only element should not be edited.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment] 2021-10-12 05:43
readonly changes for choice type widget is in progress.

**Comment by Tarun-Bhardwaj** [comment] 2021-11-18 10:17
Closing this issue as this is a duplicate of #763

**Closed by Tarun-Bhardwaj** 2021-11-18 10:17 UTC
Labels: Bug, high priority
