### ISSUE TITLE
Add AdministrativeGender ValueSet to be used by Patient Registration Questionnaire in gallery app

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#178] opened 2021-01-25 06:33 UTC
The expanded CodeSystem for the AdministrativeGender ValueSet used by the Patient Registration Questionnaire: https://www.hl7.org/fhir/codesystem-administrative-gender.json.html

**Comment by jingtang10** [comment] 2021-01-29 00:59
Duplicate of #180

**Closed by jingtang10** 2021-01-29 00:59 UTC
Labels: enhancement, reference-app
