### ISSUE TITLE
On Add patient, Phone number textbox accepting alphabets

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#868] opened 2021-10-26 07:47 UTC
**Describe the bug**
On Add patient, Phone number textbox accepting alphabets, It should accepts only numbers and some special characters

**Component**
SDC library, reference app

**To Reproduce**
1. Go to 'Reference App'
2. Click on '+' icon to add patient
3. Enter First Name, family name, Date of birth
4. Tap on phone number, Observe keyboard
5. Enter Alphabets and click on Submit button
6. Observe behaviour

**Expected behavior**
Phone number should accept numbers and some special character

**Screenshots**
![Screenshot_20211026-131415](https://user-images.githubusercontent.com/64417713/138831628-f16c752a-dfac-4648-a81a-541634678857.png)

**Smartphone (please complete the following information):**
Device: Nokia 3.4
Android version: 11
Build number: 00WW_2_410

**Comment by jingtang10** [comment] 2021-12-08 10:03
I think this is a duplicate of #650. Closing.

**Closed by jingtang10** 2021-12-08 10:03 UTC
Labels: Bug, Triage
