### ISSUE TITLE
Add Country-State-City Drop down support in SDC 

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#979] opened 2021-12-16 08:58 UTC
**Is your feature request related to a problem? Please describe.**
At the moment a user has to type in a Country and City manually and this can be an issue  saving data with inaccurate data due to user typos 

**Describe the solution you'd like**
Add the ability to select Country, State and City  from a dropdown filter list as opposed to filling an input test 

**Describe alternatives you've considered**
N/A
**Additional context**
<img src="https://user-images.githubusercontent.com/4540684/146339573-3f8815a2-f678-4bd1-8137-83f5d71e965c.png" width="300" height="300" />

**Would you like to work on the issue?**
N/A

**Comment by fredhersch** [comment] 2022-01-05 09:13
@f-odhiambo - just to clarify are you talking about dynamically populating the lists based on the selection.

So for example: If country is USA, then populate the State lists with ValueSet of states from USA and then City etc. This sounds like an example of answerExpression using FHIRPath (or CQL).

Alternatively, have you considered using a series of enableWhen options

**Comment by jingtang10** [comment] 2022-01-05 09:24
Related #965

**Comment by f-odhiambo** [comment] 2022-01-05 10:45
> @f-odhiambo - just to clarify are you talking about dynamically populating the lists based on the selection.
> 
> So for example: If country is USA, then populate the State lists with ValueSet of states from USA and then City etc. This sounds like an example of answerExpression using FHIRPath (or CQL).
> 
> Alternatively, have you considered using a series of enableWhen options 

Yes this is accurate. Will also review @jingtang10 related issue

**Comment by jingtang10** [comment] 2022-08-24 09:16
duplicate of #1039 
closing.

**Closed by jingtang10** 2022-08-24 09:16 UTC
Labels: Enhancement, Question, P1, Data capture
