### ISSUE TITLE
SDC gallery app crashed after inputing number value first in 'Year of Birth' in 'HIV Case Report With Vietnamese Translation'

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#537] opened 2021-06-06 07:39 UTC
**Describe the bug**
SDC gallery app crashed after inputing number value first in 'Year of Birth' in 'HIV Case Report With Vietnamese Translation'.
But does not crashes after inputing coma or dot first then number value, ex: ',.0123'

**Component**
SDC gallery app

**To Reproduce**
1. Go to 'HIV Case Report With Vietnamese Translation'
2. Click on 'Year of Birth'
3. Input number value first, ex: '123'
4. Crashes

**Expected behavior**
App does not crashes after inputing number value first

**Screenshots**
Will crashes after inputing number value first, ex: '123'
<img src="https://user-images.githubusercontent.com/62053304/120916148-0daff800-c6d2-11eb-9d9c-13fbe47e688b.png" width="256"> 

Does not crashes
<img src="https://user-images.githubusercontent.com/62053304/120916551-739d7f00-c6d4-11eb-99f1-32633ac55a18.png" width="256">

**Smartphone (please complete the following information):**
 - Device: [Pixel 4 emulator]
 - Android version: [11]
 - Build number: [RSR1.201013.001]
 - Version: [30]

**Additional context**
java.lang.IllegalArgumentException: Cannot compare different data types: integer and string

**Would you like to work on the issue?**
No, @maanuanubhav999 will work on this since it's similliar with issue #527 

**Device log**
> 2021-06-06 14:21:21.507 6484-6484/com.google.android.fhir.datacapture.gallery E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.fhir.datacapture.gallery, PID: 6484
    java.lang.IllegalArgumentException: Cannot compare different data types: integer and string
        at com.google.android.fhir.datacapture.validation.MoreTypesKt.compareTo(MoreTypes.kt:26)
        at com.google.android.fhir.datacapture.validation.MaxValueConstraintValidator$1.invoke(MaxValueConstraintValidator.kt:28)
        at com.google.android.fhir.datacapture.validation.MaxValueConstraintValidator$1.invoke(MaxValueConstraintValidator.kt:22)
        at com.google.android.fhir.datacapture.validation.ValueConstraintValidator.validate(ValueConstraintValidator.kt:36)
        at com.google.android.fhir.datacapture.validation.QuestionnaireResponseItemValidator.validate(QuestionnaireResponseItemValidator.kt:36)
        at com.google.android.fhir.datacapture.views.QuestionnaireItemEditTextViewHolderDelegate$init$$inlined$doAfterTextChanged$1.afterTextChanged(TextView.kt:101)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10594)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13581)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
        at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:228)
        at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
        at android.widget.TextView.doKeyDown(TextView.java:8466)
        at android.widget.TextView.onKeyDown(TextView.java:8240)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2842)
        at android.view.View.dispatchKeyEvent(View.java:14247)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4085)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5947)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5815)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)

**Comment by epicadk** [comment] 2021-06-06 08:08
Possible duplicate of #527

**Comment by FikriMilano** [comment] 2021-06-06 09:44
I think you are right @epicadk 

@maanuanubhav999 could you also check this one too?

**Comment by maanuanubhav999** [comment] 2021-06-06 10:15
thanks, @FikriMilano , I thought the issue was with quantity data type only but seems like we are comparing different data types sometimes.Will surely check on this.

**Comment by maanuanubhav999** [comment] 2021-06-06 10:57
@FikriMilano Can you just update the repository and then try to run this again.
It does not seem to occur in the latest update but prior updates have this issue.

**Comment by FikriMilano** [comment] 2021-06-06 11:35
Sorry, I think you are right. I forgot to pull the updates.

**Closed** 2021-06-06 11:35 UTC
Labels: bug

**Comment by tunm1228** [comment] 2021-07-29 11:03
> Sorry, I think you are right. I forgot to pull the updates.

I'm vietnamese. I looked at the doc but didn't understand how to install the sdk into my project. please show me the steps to do on my project. thanks a lot
