### ISSUE TITLE
Catalog, paginated layout workflow.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1072] opened 2022-01-21 11:49 UTC
**Is your feature request related to a problem? Please describe.**

1. User click on paginated  layout.
2. It launches paginated screen with questionnaire.
4. Design paginated questionnaire json.
5. Write api to fetch paginated questionnaire json file name.
6. Apply custom style at application side.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment] 2022-01-25 03:49
@shelaghm 

`Submit questionnaire' button is part of application, and not part of data capture library. But `previous and next ` buttons are part of data capture library.
There is limitation that Submit questionnaire button can not be renamed/replaced with next button.

Please see attached screenshot, as of now we are showing submit questionnaire button at the bottom of the screen.

 
<img width="429" alt="Screen Shot 2022-01-25 at 9 14 28 AM" src="https://user-images.githubusercontent.com/86107848/150907480-cc018e2f-dcd7-4d47-be22-81ef3fc0d74a.png">

**Comment by santosh-pingle** [comment] 2022-01-28 07:24
#1088

**Comment by Tarun-Bhardwaj** [comment] 2022-02-07 09:02
@santosh-pingle , PR for this issue is merged but the issue is still open. Can we close this?

**Closed** 2022-02-24 05:40 UTC
Labels: Enhancement

**Comment by Brunojoe1994** [comment] 2026-04-16 13:23
`[](https://github.com/ohs-foundation/android-fhir/blob/master/CODE_OF_CONDUCT.md)`
