### ISSUE TITLE
Prepopulate front slash while entering date

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#1720] opened 2022-11-15 09:17 UTC
**Is your feature request related to a problem? Please describe.**
While entering the date in typing mode, the current edit text field allows typing dates like 021222 even though an error pops up. 

**Describe the solution you'd like**
A request from the field workers is to automatically add the / at the right place. eg: When the user type 02 a / should be added automatically such that the user is aware that they are now entering the next part of the date. This is especially useful for less skilled workers.
![Screenshot_20221115-144100](https://user-images.githubusercontent.com/48797364/201879854-77eaf218-4e95-47c9-b24c-719ed712516e.jpg)
![Screenshot_20221115-144021](https://user-images.githubusercontent.com/48797364/201879859-c993f268-5e9d-4cab-be93-da627ab1fc31.jpg)

cc: @shelaghm

**Comment by jingtang10** [comment] 2022-11-16 16:22
hi @joiskash do people use the text input directly (without clicking the calendar icon and press the pencil icon)?

we can probably do something there.

but in this dialog there's not much we can do as this is a material dialog.

**Comment by joiskash** [comment] 2022-11-17 07:58
People use the input text directly

**Comment by shelaghm** [comment] 2022-11-29 21:57
We tested this in our usability testing and are seeing similar challenges with the date picker. We are looking into better options for entering dates. Will let you know when we have something more to share.

**Comment by jingtang10** [comment] 2023-02-13 18:23
closing this as a duplicate of https://github.com/google/android-fhir/issues/1802 which is now addressed.

**Closed by jingtang10** 2023-02-13 18:23 UTC
Labels: type:bug, P1
