### ISSUE TITLE
enableWhen not working as expected when I uncheck a checkbox

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#601] opened 2021-06-29 06:39 UTC
**Describe the bug**
I have a checkbox and two fields. If the value is

**Component**
SDC Library

**To Reproduce**
1. Check out the fh/patient-registration-questionnaire branch
2. Run the SDC Gallery app
3. Click on 'New patient registration Questionnaire (the last item)'
4. Scroll down to 'DOB Known' - in the default state you will see the field below is 'Enter age in years'
5. Check the 'DOB known' field, you will see the field below changes to 'Enter DOB' and a date picker
6. Uncheck the 'DOB Known'
7. Error state is that the field doesn't change back

**Expected behavior**
Should toggle the field options based on selecting/unselecting the checkbox

**Smartphone (please complete the following information):**
 - Device: Virtual device
 - Android version: 29

**Comment by jingtang10** [comment] 2021-07-01 08:55
Duplicate of #530

**Closed by jingtang10** 2021-07-01 08:55 UTC
Labels: bug
