### ISSUE TITLE
FHIR Engine | Upload Bundle transaction containing only delete resource request when resource created & deleted locally.

### ISSUE THREAD

**Issue by ppanchal-argus** [google/android-fhir#2031] opened 2023-06-11 22:59 UTC
**Describe the bug**
Locally when a resource is created & then deleted & later when the app is synced. The upload transaction bundle only contains the delete request of the resource, not the create. Ideally either the delete request shall not be sent or both create & delete request must be included.

I have attached a patch file to demonstrate this issue & attaching the upload bundle as well as the response bundle.

**Component**
Core library.

**To Reproduce**
1. On Master branch apply the patch [resources_create_and_delete.txt](https://github.com/google/android-fhir/files/11715957/resources_create_and_delete.txt)

2. Run the app, Go to new questionnaire (+ icon n patient list)
3. Submit the questionnaire as it is (Submit anyway)
4. Now the observationA is created and deleted, observationB is only created
5. Hit submit and check the upload request and response on logcat (might need to set level to debug).

Upload Bundle: [upload_transaction_bundle.txt](https://github.com/google/android-fhir/files/11715946/upload_transaction_bundle.txt)

Response bundle: [resoponse_bundle.txt](https://github.com/google/android-fhir/files/11715947/resoponse_bundle.txt)

**Expected behavior**
Since the resource is created & deleted locally, Either the delete request shall not be sent or both create & delete request must be included.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

cc: @jingtang10

**Comment by jingtang10** [comment] 2023-07-27 09:25
@anchita-g fyi

**Comment by jingtang10** [comment] 2023-07-27 09:26
can you check if this can be resovled by your change?

**Comment by anchita-g** [comment] 2023-07-27 09:34
This largely is dependent on the way we squash changes. Once we merge my changes, a minor fix in the either the way we squash changes can solve this.

**Comment by omarismail94** [comment] 2023-08-14 09:52
@MJ1998  Im just looking at the PR you submitted and Im not sure if it solves the problem cleanly. Have you thought about creating a special No-op Type. This way, you need to modify the squash function to handle the case where an object is created and deleted before syncing. Specifically, if a Type.INSERT operation is followed by a Type.DELETE operation for the same object, these operations should be squashed into a no-op (i.e., no operation should be sent to the server):


```
private fun mergeLocalChanges(first: LocalChange, second: LocalChange): LocalChange {
  // TODO (maybe this should throw exception when two entities don't have the same versionID)
  val type: Type
  val payload: String
  when (second.type) {
    Type.UPDATE ->
      when (first.type) {
        Type.UPDATE -> {
          type = Type.UPDATE
          payload = mergePatches(first.payload, second.payload)
        }
        Type.INSERT -> {
          type = Type.INSERT
          payload = applyPatch(first.payload, second.payload)
        }
        else -> {
          throw IllegalArgumentException(
            "Cannot merge local changes with type ${first.type} and ${second.type}."
          )
        }
      }
    Type.DELETE ->
      when (first.type) {
        Type.INSERT -> {
          return LocalChange(
            resourceId = second.resourceId,
            resourceType = second.resourceType,
            type = Type.NO_OP,
            payload = "",
            versionId = second.versionId,
            token = LocalChangeToken(first.token.ids + second.token.ids),
            timestamp = second.timestamp
          )
        }
        else -> {
          type = Type.DELETE
          payload = ""
        }
      }
    Type.INSERT -> {
      type = Type.INSERT
      payload = second.payload
    }
  }
  return LocalChange(
    resourceId = second.resourceId,
    resourceType = second.resourceType,
    type = type,
    payload = payload,
    versionId = second.versionId,
    token = LocalChangeToken(first.token.ids + second.token.ids),
    timestamp = second.timestamp
  )
}
```

can you test this and see if it simplifies things

**Comment by omarismail94** [comment] 2023-08-14 16:04
@ppanchal-argus  can you cherry-pick the changes in P# #2133 and see if that fixes this issue? I tested on my end and the issue seems resolved

**Comment by jingtang10** [comment] 2023-08-16 10:17
thanks omar for the fix. i think this issue is a duplicate of #1951.

closing. parth - please reopen if this is still not fixed.

**Closed by jingtang10** 2023-08-16 10:17 UTC
Labels: P1, effort:small
