### ISSUE TITLE
Subsequent OneTime sync triggers always start with CurrentSyncJobStatus.SUCCEDED status

### ISSUE THREAD

**Issue by ndegwamartin** [google/android-fhir#2472] opened 2024-03-12 09:46 UTC
**Describe the bug**
When One time sync is triggered again, the state is first retrieved from the `syncJobStatusFromWorkManager`(screenshot). A null check is performed and if the state returned is null the [state is retrieved from the sync job status datastore](https://github.com/google/android-fhir/blob/9697a8a01283f38a9c2b20e8e3608cfc00bd9e7e/engine/src/main/java/com/google/android/fhir/sync/Sync.kt#L276). This will hold the status of the previous one time sync.

This means that on subsequent one time syncs, we have no way of capturing the state that a new sync has started. This is important so that for instance we can show a UI that shows _Sync process is starting_. The main issue with the UX is that every time we trigger it subsequently, it first  shows a **Sync complete** dialog then it proceds to do the actual sync after which it shows the _sync complete dialog_ again. 

**Component**
Core library

**To Reproduce**
- Trigger a one time sync multiple times

**Expected behavior**
We should always return a job status like `Running.Started` or `Enqueued` for every fresh onetime sync trigger in order to update UX accordingly.

**Screenshots**
![Screenshot 2024-03-12 at 12 15 46](https://github.com/google/android-fhir/assets/10017086/0a6147c1-5e57-4b68-ad87-32cad3b4af9c)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Would you like to work on the issue?**
Sure, however @santosh-pingle recently worked on the original feature

**Comment by MJ1998** [comment] 2024-03-12 16:08
Thanks @ndegwamartin for identifying this. 
@santosh-pingle I think this should be a small change ?

**Comment by santosh-pingle** [comment] 2024-04-15 08:01
Looking into it.

**Comment by santosh-pingle** [comment] 2024-04-16 13:14
@ndegwamartin Can you please check whether the issue is fixed with this change #2511

**Comment by ndegwamartin** [comment] 2024-04-19 11:08
Yeah this fixes it, left a comment on the PR

**Closed** 2024-07-05 13:51 UTC
Labels: type:enhancement, P2
