### ISSUE TITLE
SDC beta04: Tapping on date picker does not bring up keyboard/picker except for just the icon on the far right

### ISSUE THREAD

**Issue by williamito** [google/android-fhir#1555] opened 2022-08-12 19:16 UTC
**Describe the bug**
Tapping on date picker does not bring up keyboard/picker except for just the icon on the far right.

**Component**
SDC Library

**To Reproduce**
1. Load a questionnaire with a date field
2. Tap the date field in the area without the icon
3. The field is selected but no entry mechanism is provided

**Expected behavior**
The date picker or a keyboard appears

**Screenshots**

https://user-images.githubusercontent.com/7772901/184428043-03d785a6-81b1-457d-9b9e-fef00d7b9148.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 4

**Comment by PallaviGanorkar** [comment] 2022-08-18 07:22
Feature is under development in PR https://github.com/google/android-fhir/pull/1493

**Comment by Tarun-Bhardwaj** [comment] 2022-08-18 11:38
> Feature is under development in PR #1493

Closing this issues as it is a duplicate of #1418 and is already being addressed.

**Closed by Tarun-Bhardwaj** 2022-08-18 11:38 UTC
Labels: Bug
