### ISSUE TITLE
SDC library does not render valueSet widgets on the Questionnaire

### ISSUE THREAD

**Issue by ndegwamartin** [google/android-fhir#928] opened 2021-11-18 12:54 UTC
**Describe the bug**
For Open Choice items configured with the answer format value sets i.e. _answerValueSet_, the widgets _Do Not_ render successfully on the Questionnaire. This can be observed with the  HIV Case Report questionnaire **Occupation** form field.

**Component**
SDC library

**To Reproduce**
1. Go to the _Data Capture Gallery_ home page
2. Click on _HIV Case Report_
3. Scroll down to _Occupations_ or _Risk Factors_
4. Confirm that the corresponding widgets do not render

**Expected behavior**
The questionnaire should render the open-choice widget when the answer format is defined as a _valueSet_
See the _open-choice answerFormats in Questionnaire_ ticket with attached screenshot here #689

**Screenshots**
See the **Occupation** and **Risk Factor** fields in the HIV Case Report questionnaire screenshot below
![Screenshot](https://user-images.githubusercontent.com/10017086/142413625-f8a5b0c1-223c-412c-9394-6530c7f1e6fa.png)

**Smartphone (please complete the following information):**
 - Device: _Nexus 7 2012 Emulator_
 - Android version: **9.0(Pie ) - API 28**
 - Build number: **sdk_gphone_x86-userdebug 9 PSR1.180720.093**
 - Version: **(1)1.0.0** 

**Additional context**
This bug needs to be fixed before issue #552 can be implemented/closed

**Would you like to work on the issue?**
`@kevinmost` contributed to the the working implementation as assigned here #801

**Comment by jingtang10** [comment] 2021-11-24 17:27
@wantingzhang77 will work on this

**Comment by wantingzhang77** [comment] 2021-12-01 05:17
@jingtang10 I am looking at this issue and just have a few questions:     
Currently our library can't handle all Questionnaire.Items with attribute "type: choice" and attribute "answerValueSet" correctly.
![image](https://user-images.githubusercontent.com/30681022/144174674-d978fcf3-1378-4f0a-8519-8adff363e5d2.png)

(1) in QuestionnaireItemAdapter.kt, `getChoiceViewHolderType()` is the function used to decide the viewHolderType. `getChoiceViewHolderType()` looks at the `itemControl` which is missing in these `QuestionnaireItems`, then `QuestionnaireItemViewHolderType.RADIO_GROUP` is used as a default type. I am not sure if this is intended behavior but it looks a little weird to me. Should we add the `itemControl` to these questions? I am not sure if touch these json questionnaire example is the right thing to do.

(2) I assume the `answerValueSet` are the answers should be rendered. I tried those url in my browser(for example: http://openhie.org/fhir/hiv-casereporting/ValueSet/vs-hiv-population) but the browser can not open it. Do you know how should we process these `answerValueSet` urls?

**Comment by jingtang10** [comment] 2021-12-08 18:17
@wantingzhang77 thanks for looking into this. You're right `answerValueSet` is the field that contains the answers to be rendered. Please see more info here https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.answerValueSet

The URL in the answer value set does not necessarily correspond to a real URL. It can just be a unique identifier for the value set.

Looking at this implementation guide https://openhie.github.io/hiv-ig/ and especially the list of artifacts: https://openhie.github.io/hiv-ig/artifacts.html it appears to me the value set with url `http://openhie.org/fhir/hiv-casereporting/ValueSet/vs-hiv-population` is just missing. We need to find out from the IG authors if that's the case.

Once we locate the answer value set with the URL though, we need to either add this to the questionnaire as one of "contained" resources, or provide a custom answer value set provider (@aditya-07 can help with this).

**Comment by wantingzhang77** [comment] 2021-12-08 18:49
@jingtang10 I found this webpage: [https://openhie.github.io/hiv-ig/ValueSet-vs-key-population.html](https://openhie.github.io/hiv-ig/ValueSet-vs-key-population.html). Looks like it contains answers that may corresponding to the hiv-population questionnaire.Item. Just not sure if this is the right way to go. 
If it is, is that the URL incorrect for this questions item? How should we get the answerValueSet from the webpage?

**Comment by costateixeira** [comment] 2021-12-08 20:25
Hi @wantingzhang77 Can you please point to where you found the reference to vs-key-population? I can only find the hiv-population and it may be an incomplete rename... I think indeed that the ValueSet is vs-key-population

As @jingtang10 says, the URL is not always expected to resolve. When it doesn't resolve, the ImplementationGuide that contains the Questionnaire should also contain the expanhttps://openhie.github.io/hiv-ig/expansions.jsonded ValueSet - but this is not always guaranteed and we're working on ways to fix it.


An detail hint that might help in the implementation: When the ImplementationGuide defines the value sets, there is a file called `expansions.json` that contains the expanded valuesets. 
For example, the ImplementationGuide https://openhie.github.io/hiv-ig 
has a file called https://openhie.github.io/hiv-ig/expansions.json where you can find the expanded valueset - for example search for http://openhie.org/fhir/hiv-casereporting/ValueSet/vs-key-population

**Comment by jingtang10** [comment] 2021-12-09 16:25
@costateixeira, we took the questionnaire from the URL: https://openhie.github.io/hiv-ig/Questionnaire-hiv-case-report-questionnaire.json.html but I think I'm getting 404 now so assuming it's been moved, but not have had luck finding it now in the artifact index on the IG home page.

What's important in this issue for us to verify is just that there *IS* a way to render these quetions with the answer value set --  once we can confirm that, we might be able to close this issue without code change because the data capture gallary app is due to be changed.

**Comment by costateixeira** [comment] 2021-12-09 16:49
@jingtang10 if you want to use a questionnaire sample, you can use this one:
https://openhie.github.io/case-reporting/Questionnaire-case-reporting-questionnaire.html
(also at the end of that page you have notes about the several ways a ValueSet may appear - these were actually created for you to have some test cases): https://openhie.github.io/case-reporting/Questionnaire-case-reporting-questionnaire.html#notes
in this Questionnaire, you can see for example the patient gender ValueSet available here: https://openhie.github.io/case-reporting/expansions.json
This is because the Patient Gender is defined in this ImplementationGuide. For Ethnicity, the way the ValueSet is defined is not allowing the VS to be expanded.

I don't recall why the other one is 404'ing, there was a merge from Jembi team and I don't know if that is when we lost it..

**Comment by jingtang10** [comment] 2021-12-10 13:45
Thanks Jose.

So this does sound like a data issue with the previous version of the questionnaire. With @shelaghm working on revamping the demo app, I'm tempted to say let's not spend time on this questionnaire itself.

@wantingzhang77 - but I still think it's worth testing that the flow actually works, if you want to do some local testing to see the newer version of the questionnaire Jose provided works with the APIs in our code. If everything seems fine, I'm happy for us to close this issue.

@anita-vadverao this needs to be added to test scenarios as well.

**Comment by vishnuravi** [comment] 2022-08-09 12:30
@jingtang10 I have noticed that the options defined in `answerValueSet` do not render even if they are defined in the Questionnaire itself, such as this example SDC-PHQ9 Questionnaire: http://build.fhir.org/ig/HL7/sdc/Questionnaire-questionnaire-sdc-profile-example-PHQ9.json.html. Is there something additionally I would need to do to render these options?

**Comment by fredhersch** [comment] 2022-08-16 12:26
> @jingtang10 I have noticed that the options defined in `answerValueSet` do not render even though they are defined in the Questionnaire itself, such as this example SDC-PHQ9 Questionnaire: http://build.fhir.org/ig/HL7/sdc/Questionnaire-questionnaire-sdc-profile-example-PHQ9.json.html. Is there something additionally I would need to do to render these options?

Thanks @vishnuravi can you send a screenshot of what happens when you render this

@jingtang10 Could this be an issue with the ordinalValue extension? Or is it the way the valueSet is defined.. appears to be an example of "contained" valueSet options

cc: @wantingzhang77

**Comment by vishnuravi** [comment] 2022-08-16 15:47
Hi @fredhersch thanks for looking into this! When I render the Questionnaire, the questions appear, but the answer options don't.

<img width="319" alt="Screen Shot 2022-08-16 at 11 47 28 AM" src="https://user-images.githubusercontent.com/1212163/184922797-c9acdc61-21a5-4c9b-9fe4-1ca5717b1200.png">

Appreciate any advice you have on this issue!

**Comment by costateixeira** [comment] 2022-08-16 16:20
Hi

I see the valueset is done by listing the concepts in compose.include,
perhaps what is needed is the expanded value set where the codes would show
up in expansion.contains

see this example:
https://build.fhir.org/valueset-example-expansion.json.html

Not sure this would be the issue but I expect that the tool needs to look
at the final valueset, regardless of how the valueset is defined, and that
is in expansion.

Cheers

José

**Comment by williamito** [comment] 2022-09-07 20:42
The core issue appears to be that the SDC Library can parse the `.expansion` version of codes, and not `.compose`.

From [ValueSet](https://www.hl7.org/fhir/valueset.html):

> Value sets have 2 aspects:
> 
> [.compose](https://www.hl7.org/fhir/valueset-definitions.html#ValueSet.compose): A definition of which codes are intended to be in the value set ("intension")
> [.expansion](https://www.hl7.org/fhir/valueset-definitions.html#ValueSet.expansion): The list of codes that are actually in the value set under a given set of conditions ("extension") - see [Value Set Expansion](https://www.hl7.org/fhir/valueset.html#expansion)
>
> The ValueSet resource can carry either the .compose or the .expansion, both of them, or neither of them (if only the metadata is being represented). There is an ["$expand" operation](https://www.hl7.org/fhir/valueset-operation-expand.html) which can be used to ask a server to generate an expansion given the composition rules, in a particular context, and a ["$validate-code" operation](https://www.hl7.org/fhir/valueset-operation-validate-code.html) which can be used to ask a server to check whether a given code or concept is in the value set in a particular context.

To my understanding these two questionnaires with included valuesets should be equivalent but only the first works.

Working:
```json
{
  "resourceType": "Questionnaire",
  "contained":
  [
    {
      "resourceType": "ValueSet",
      "id": "yesnodontknow",
      "expansion":
      {
        "contains":
        [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0136",
            "code": "Y",
            "display": "Yes"
          },
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0136",
            "code": "N",
            "display": "No"
          },
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0136",
            "code": "asked-unknown",
            "display": "Don't Know"
          }
        ]
      }
    }
  ],
  "item":
  [
    {
      "linkId": "1",
      "type": "choice",
      "text": "Does this work?",
      "answerValueSet": "#yesnodontknow"
    }
  ]
}
```

Not Working:
```json
{
  "resourceType": "Questionnaire",
  "contained":
  [
    {
      "resourceType": "ValueSet",
      "id": "yesnodontknow",
      "compose":
      {
        "include":
        [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0136",
            "concept":
            [
              {
                "code": "Y",
                "display": "Yes"
              },
              {
                "code": "N",
                "display": "No"
              },
              {
                "code": "asked-unknown",
                "display": "Don't Know"
              }
            ]
          }
        ]
      }
    }
  ],
  "item":
  [
    {
      "linkId": "1",
      "type": "choice",
      "text": "Does this work?",
      "answerValueSet": "#yesnodontknow"
    }
  ]
}
```

**Comment by fredhersch** [comment] 2022-10-03 12:04
@jingtang10 My understanding was this is a small change. Is this still open?

**Comment by jingtang10** [comment] 2024-02-26 13:52
@ndegwamartin can you please confirm if this is still an issue?

**Comment by costateixeira** [comment] 2024-02-26 13:58
Hi All

Just for scoping:
If the expectation is that all valuesets need to be expanded for passing to
the SDK, then this requirement would no longer apply, as at the end, even
with compose, the valuesets would have the expansion.

Compose is used in defining valuesets I wouldn't set any tooling
expectations on it, because some valuesets will be intensionally defined
and there the .compose will not contain the codes. So at the end, what
would matter is the .expand.

Cheers

José

**Comment by ndegwamartin** [comment] 2024-02-27 11:51
@jingtang10 I concur with @williamito and @costateixeira's findings and additionally with your observation that it is a data issue _(retrieved a versioned copy of the [HIV case report questionnaire json](https://github.com/google/android-fhir/blob/3f3e137bd415e95b92fa798c236d9b3efa954870/datacapturegallery/src/main/assets/openhie-hiv-case-report.json) to review/test this out)_ which can be solved by re-authoring the questionnaire to use `expansions.contains`. 

Given the above then this is no longer an issue and we can close this ticket cc @f-odhiambo

**Comment by jingtang10** [comment] 2024-02-27 14:07
thanks @ndegwamartin and all!

**Closed by jingtang10** 2024-02-27 14:07 UTC
Labels: P1
