### ISSUE TITLE
Add a SyncJobStatus result callback amid Sync retries

### ISSUE THREAD

**Issue by ndegwamartin** [google/android-fhir#2049] opened 2023-06-26 22:11 UTC
**Is your feature request related to a problem? Please describe.**
Currently, there is no way for reliant apps to obtain the exceptions from backend calls until all Sync retries are completed by the **FhirSyncWorker** class. Our app would like to process the exceptions as soon as they happen.

**Describe the solution you'd like**
We'd like to add an abstract method to the `FhirSyncWorker.kt` class that would need to be implemented by the reliant app. It should accept a parameter of type `SyncJobStatus`.

For example:
```kotlin
abstract fun onSyncJobResult(syncJobStatus: SyncJobStatus)
```

It should then be invoked within the `FhirSyncWorker.doWork` method after the result is obtained.

**Describe alternatives you've considered**
We could also just log the failures in an _open_ method that could be _overridden_ by the reliant app. This way they'd have the ability to obtain the exceptions that are part of the `SyncJobStatus.Failed` instance. The SDK could log those errors in its implementation(as default).

For example:
```kotlin
open fun onFailedSyncJobResult(failedSyncJobStatus: SyncJobStatus.Failed){
     Timber.e(failedSyncJobStatus.exceptions);
}
```

**Additional context**
N/A

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment] 2023-09-07 09:37
@santosh-pingle

**Comment by santosh-pingle** [comment] 2024-02-05 07:15
duplicate of # https://github.com/google/android-fhir/issues/2049

**Comment by fredhersch** [comment] 2024-02-07 03:34
Closing. Will track in #2203

**Comment by santosh-pingle** [comment] 2024-02-07 05:08
> ~duplicate of # #2049~
> 
> EDITED by @jingtang10
my bad, I mentioned the same issue.

@aditya-07 https://github.com/google/android-fhir/issues/2371  are these similar issues?

**Comment by jingtang10** [comment] 2024-02-07 05:41
closing in favour of #1654

**Closed by jingtang10** 2024-02-07 05:41 UTC
Labels: P1
