### ISSUE TITLE
Incorrect number of Patients in Reference App

### ISSUE THREAD

**Issue by Manikant25** [google/android-fhir#596] opened 2021-06-27 08:30 UTC
**Describe the bug**
There are 20 patients in the Patient's List view but on top it is showing 24 Patient(s) in textview.

**Component**
reference app

**To Reproduce**
1. Go to 'reference app'
2. See error

**Expected behavior**
It should have shown 20 Patient(s).

**Screenshots**
Not needed as such.

**Smartphone (please complete the following information):**
 - Device: xiaomi mi a3
 - Android version: 11
 - Build number: 11 RKQ1.200903.002 V12.0.9.0.RFQMIXM

**Additional context**
N/A

**Would you like to work on the issue?**
Yes

**Comment by FikriMilano** [comment] 2021-06-27 12:08
@Manikant25 possible duplicate of #563 ?

**Comment by Manikant25** [comment] 2021-06-27 12:15
> @Manikant25 possible duplicate of #563 ?

No, it is not. Open reference app it shows 20 patients on the list But on Top, it shows that there are 24 Patients on textview

**Comment by Ana2k** [comment] 2021-06-28 18:08
> > @Manikant25 possible duplicate of #563 ?
> 
> No, it is not. Open reference app it shows 20 patients on the list But on Top, it shows that there are 24 Patients on textview

A possible API sync error then?
@FikriMilano what do you say?

**Comment by aditya-07** [comment] 2021-06-28 18:36
Reference App limits to showing max 20 patients in the app irrespective of the number of patients in the db. 
The top textview is however showing the actual count of patients in the db based on the criteria.

Good first bug if someone wants to fix it in the Reference App.

**Comment by Ana2k** [comment] 2021-07-01 07:10
@aditya-07 I am thinking of linking a pr soon to this since I am working on the reference app itself

**Comment by FikriMilano** [comment] 2021-07-01 08:41
> 
> 
> > > @Manikant25 possible duplicate of #563 ?
> > 
> > 
> > No, it is not. Open reference app it shows 20 patients on the list But on Top, it shows that there are 24 Patients on textview
> 
> A possible API sync error then?
> @FikriMilano what do you say?

No, I think it's because of:

1. The MAX_RESOURCE_COUNT is limited to 20. This is why the PatientList only render maximum 20 items
https://github.com/google/android-fhir/blob/79681c2c22683be94bb498d13ff0403d55d4392d/reference/src/main/java/com/google/android/fhir/reference/MainActivity.kt#L29

2. The getSearchResults() has different filter compared to count(). Even after MAX_RESOURCE_COUNT got increased, we still need to add a filter in order to show the right amount of PatientList
https://github.com/google/android-fhir/blob/79681c2c22683be94bb498d13ff0403d55d4392d/reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt#L65
https://github.com/google/android-fhir/blob/79681c2c22683be94bb498d13ff0403d55d4392d/reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt#L56


Here is a screenshot: (as you can see there are also duplication on patient 21 and 22, will notify #563 soon)

<img src="https://user-images.githubusercontent.com/62053304/124091011-975ba700-da7f-11eb-9564-7efce0a586ca.png"  width="256">

**Comment by santosh-pingle** [comment] 2021-07-01 10:25
@FikriMilano 

#563
Above mentioned Patient duplication does not belong to same patient resource id.
It happened to be two patient resources are having same records with different resource id.

Please see below screenshots.

<img width="1323" alt="Screen Shot 2021-07-01 at 3 40 09 PM" src="https://user-images.githubusercontent.com/86107848/124108661-fb806a00-da83-11eb-9682-61129c365c89.png">


<img width="1359" alt="Screen Shot 2021-07-01 at 3 39 09 PM" src="https://user-images.githubusercontent.com/86107848/124108523-e4da1300-da83-11eb-9fa0-fd213227fc39.png">

**Comment by FikriMilano** [comment] 2021-07-01 10:51
@santosh-pingle
I see, you're right. Thanks for the explanation

**Closed** 2021-09-09 14:44 UTC
Labels: bug, good first issue
