### ISSUE TITLE
Language settings in phone for appropriate date format display

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#1721] opened 2022-11-15 09:31 UTC
**Describe the issue to be researched**
The date picker in the SDC library is using the default language of the phone to display the date format prompt eg:

English US will display date as m/d/yy
English Nigeria will display date as d/m/yy

Some phones have very limited language selection settings as shown in the screen shots below. 

Language set to English US
![US_English](https://user-images.githubusercontent.com/48797364/201881204-44dd2643-6d32-4185-8453-e9a1cf66755f.jpg)

Language set to Hindi
![Hindi](https://user-images.githubusercontent.com/48797364/201881261-0f0183a5-5aa0-4efa-b217-4398ca2e14d1.jpg)

Other language selection options:
![Language_options](https://user-images.githubusercontent.com/48797364/201881443-a42e219c-db2a-47a8-9488-ba038e913b6b.jpg)

**Describe the goal of the research**
The above screen shots shows how phone purchased in a particular geographical location may not have the right locale inbuilt by default. This will result in confusing date formats displayed while capture date using the SDC library. The screenshots above are from a phone purchased in India. Indians use the date format d/m/yy which can be seen when selecting a local language eg: Hindi. But if we want to allow users to also use English, the date format will be m/d/yy which is confusing and can lead to data input errors considering low skilled workers using the app.
The goal of this research is to figure out how to add more languages to the phone such that initial setups can be done correctly by technical people before putting the device for use in field
Alternatively what software solutions are available and how do app developers deal with locale?

**Describe the methodology**
Where can more information be found? Who should the assignee approach to ask questions? How can a decision be made?

**Would you like to work on the issue?**

cc: @jingtang10 @aditya-07 @shelaghm

**Comment by PallaviGanorkar** [comment] 2022-11-16 06:04
@joiskash  Please provide more details about android device, android version, SDC lib version used.

**Comment by joiskash** [comment] 2022-11-16 06:14
Device - Infinix Hot 11 play X688B Made in India
Android Version - 11
OS - XOS Dolphin v7.6.0
SDC lib - sdc-0.1.0-beta06

**Comment by shelaghm** [comment] 2022-11-16 16:29
@williamito is this something you can help add some documentation on our wiki?

**Comment by jingtang10** [comment] 2022-11-16 16:31
Hi @joiskash in the languages settings in android you can set the order of different language+locale. i think the first one becomes the system's default for applications.

in my testing, i have English UK and English US as the top 2 languages, reordering them would result in different entry format strings in the sdc catalog app. notice if you're testing this you might need to kill and restart the app.

**Comment by joiskash** [comment] 2022-11-16 19:12
Yes that's what we have done in the screenshots above. We have changed the language and it has resulted in the appropriate date format. 
The main issue that I want to bring up is that this particular phone does not have English (India).
Similarly they do not have English (Nigeria). 
A samsung phone purchased in India and Nigeria does have the appropriate locale. So we cannot guarantee that a phone purchased in a region will have the appropriate locale set. This is mainly a problem for English.

**Comment by jingtang10** [comment] 2022-11-21 14:33
Just to clarify that the issue is that in some phones certain locales don't seem to be available so the device cannot be configured to the same locale as other devices used for the same programme. So the solution being proposed here is that we use the entry format string defined in the questionnaire to override the system defined date/time format string for the locale.

**Comment by shelaghm** [comment] 2023-01-11 22:28
Outcomes from Usability testing: 
- Relying on on-device date format can lead to unintended consequences and confusion. 
- Devices may not have been setup correctly. 
- Country specific software format might not match user mental models or expectation.

Proposed solution is to have developers/implementers define the date format somewhere. I'm not sure on the technical solution for this, so please add your thoughts @jingtang10 @joiskash What do you think?

**Comment by jingtang10** [comment] 2023-03-06 21:27
Thanks @shelaghm and @joiskash for the discussion. I think we have decided that we're going to support entry format as a solution to this problem. This work is captured in #1850. 

**BUT** we need to clarify that the pop up dialog we use is a material component. As a result we don't have any control over it as it's an external dependency to the sdc library. So, we can only support entry format in the text input itself, not in the material date/time picker dialogs.

This is a source of concern in terms of inconsistency. But I feel it is a price we'd have to pay for supporting entry format.

@shelaghm are you satisfied with this conclusion? and if so can we close this issue? thanks

**Comment by shelaghm** [comment] 2023-03-06 21:33
@jingtang10 Yes, agreed. I think entry format support is the best solution to move forward with, and we are aligning on specifics within #1850. We can close this issue

**Closed by shelaghm** 2023-03-06 21:33 UTC
Labels: P2, effort:medium
